str = input("Input your message: ")
print("Third symbol is: ", str[2])
print("Penultimate symbol is: ", str[-2])
print("First five symbols is: ", str[0: 5])
print("New string is: ", str[0:len(str)-2])
print("Another string with couples indeces is: ", str[0::2], "\n\n")
print("Another string with odd indeces is: ", str[1::2], "\n\n")
print("New string is: ", str[len(str)+1::-1])
print("New 2 string is: ", str[len(str)+1::-2])
print(len(str))